services:
  pet-adoption:
    ports:
      - 5002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PetAdoptionContext=Server=pet-adoption-db;Database=PetAdoption;User=root;Password=Password123!
    deploy:
      restart_policy:
        condition: on-failure

  pet-adoption-db:
    environment:
      - "MYSQL_ROOT_PASSWORD=Password123!"
    volumes:
      - pet-adoption-db-data:/var/lib/mysql

volumes:
  pet-adoption-db-data: