version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AdoptyConnection=Server=db;Database=Adopty;User=sa;Password=P@ssw0rd;TrustServerCertificate=true;
      - ConnectionStrings__IdentityConnection=Server=db;Database=Identity;User=sa;Password=P@ssw0rd;TrustServerCertificate=true;
      - RabbitMq__Host=rabbitmq
      - Services__Identity__Url=http://localhost:5001
      - Services__Adopty__Url=http://localhost:5002
      - Swagger__OAuth2__TokenUrl=http://localhost:5001/connect/token
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
